# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-24 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HackOkapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lost',
            name='created',
        ),
        migrations.RemoveField(
            model_name='lost',
            name='updated',
        ),
        migrations.AddField(
            model_name='lost',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
